import { User, Post, Reel, Story, MediaAsset } from './types';
import { generateUsers } from './user-generator';
import { PRESET_VIDEO_CLIPS } from './video-library';

export const SEED_USERS: User[] = generateUsers();

// 24H Stories
export const SEED_STORIES: Story[] = [
  {
    id: 'story_1',
    userId: 'usr_customer',
    user: {
      id: 'usr_customer',
      username: 'customer',
      name: 'Alex Rivera',
      avatarUrl: '/pics/pic_05.jpg',
      isVerified: true,
    },
    mediaUrl: '/pics/pic_11.jpg',
    resourceType: 'image',
    durationSeconds: 6,
    expiresAt: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    isSeen: false,
  },
  {
    id: 'story_2',
    userId: 'usr_feat_1',
    user: {
      id: 'usr_feat_1',
      username: 'sophia_visuals',
      name: 'Sophia Vance',
      avatarUrl: '/pics/pic_01.jpg',
      isVerified: true,
    },
    mediaUrl: '/videos/reel_06.mp4',
    resourceType: 'video',
    durationSeconds: 15,
    expiresAt: new Date(Date.now() + 23 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isSeen: false,
  },
  {
    id: 'story_3',
    userId: 'usr_feat_2',
    user: {
      id: 'usr_feat_2',
      username: 'marcus_lens',
      name: 'Marcus Chen',
      avatarUrl: '/pics/pic_03.jpg',
      isVerified: true,
    },
    mediaUrl: '/videos/reel_01.mp4',
    resourceType: 'video',
    durationSeconds: 15,
    expiresAt: new Date(Date.now() + 20 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isSeen: false,
  },
  {
    id: 'story_4',
    userId: 'usr_feat_3',
    user: {
      id: 'usr_feat_3',
      username: 'elena_captures',
      name: 'Elena Rostova',
      avatarUrl: '/pics/pic_04.jpg',
      isVerified: true,
    },
    mediaUrl: '/videos/reel_04.mp4',
    resourceType: 'video',
    durationSeconds: 13,
    expiresAt: new Date(Date.now() + 16 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    isSeen: false,
  },
  {
    id: 'story_5',
    userId: 'usr_feat_4',
    user: {
      id: 'usr_feat_4',
      username: 'kai_cinema',
      name: 'Kai Tanaka',
      avatarUrl: '/pics/pic_06.png',
      isVerified: true,
    },
    mediaUrl: '/videos/reel_21.mp4',
    resourceType: 'video',
    durationSeconds: 15,
    expiresAt: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 3600 * 1000).toISOString(),
    isSeen: false,
  },
];

const DIVERSE_CREATORS = [
  'sophia_visuals',
  'marcus_lens',
  'elena_captures',
  'kai_cinema',
  'chloe_art',
  'liam_motion',
  'maya_studio',
  'customer',
  'leo_craft',
  'zoe_frames',
  'aria_aesthetic',
  'noah_wildlife',
  'mira_architect',
];

// Rich Library of Real Instagram Video Reels (From VIDEOS folder)
export const SEED_REELS: Reel[] = PRESET_VIDEO_CLIPS.map((clip, index) => {
  const directMatch = clip.creatorUsername
    ? SEED_USERS.find((u) => u.username.toLowerCase() === clip.creatorUsername.toLowerCase())
    : null;
  const targetUsername = directMatch ? directMatch.username : DIVERSE_CREATORS[index % DIVERSE_CREATORS.length];
  const author = SEED_USERS.find((u) => u.username.toLowerCase() === targetUsername.toLowerCase()) || SEED_USERS[index % 10];

  return {
    id: `reel_${String(index + 1).padStart(2, '0')}`,
    postId: `post_reel_${String(index + 1).padStart(2, '0')}`,
    userId: author.id,
    user: {
      id: author.id,
      username: author.username,
      name: author.name,
      avatarUrl: author.avatarUrl,
      isVerified: author.isVerified,
    },
    videoUrl: clip.videoUrl,
    posterUrl: `${clip.videoUrl}#t=0.001`,
    audioTrackTitle: clip.audioTrackTitle,
    caption: clip.caption,
    likesCount: clip.likesCount,
    commentsCount: clip.commentsCount,
    sharesCount: Math.floor(clip.likesCount * 0.12),
    viewsCount: clip.viewsCount,
    duration: clip.duration,
    isLiked: index % 3 === 0,
    isBookmarked: index % 4 === 0,
    createdAt: new Date(Date.now() - (index + 1) * 3600 * 1000 * 6).toISOString(),
  };
});

// Feed Photo Posts
const INITIAL_PHOTO_POSTS: Post[] = [
  {
    id: 'post_01',
    userId: 'usr_customer',
    user: {
      id: 'usr_customer',
      username: 'customer',
      name: 'Alex Rivera',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
      isVerified: true,
    },
    caption: 'Neon reflections in the heart of Shinjuku at 2 AM. Processed via Cloudinary dynamic color enhancement & edge optimization. 🌃✨ #tokyo #cyberpunk #streetphotography',
    location: 'Shinjuku, Tokyo',
    visibility: 'public',
    media: [
      {
        id: 'media_01_1',
        userId: 'usr_customer',
        postId: 'post_01',
        assetId: 'cld_shinjuku_01',
        publicId: 'beesocial/posts/images/post_01/neon_shinjuku',
        resourceType: 'image',
        format: 'webp',
        width: 1200,
        height: 1500,
        bytes: 1310837,
        originalUrl: '/pics/pic_17.jpg',
        thumbnailUrl: '/pics/pic_17.jpg',
        optimizedUrl: '/pics/pic_17.jpg',
        folder: 'beesocial/posts/images',
        tags: ['tokyo', 'neon', 'night', 'street'],
        createdAt: '2026-03-28T14:20:00.000Z',
      },
    ],
    likesCount: 384,
    commentsCount: 18,
    sharesCount: 29,
    isLiked: false,
    isBookmarked: false,
    tags: ['tokyo', 'cyberpunk', 'streetphotography'],
    comments: [
      {
        id: 'comm_01_1',
        postId: 'post_01',
        userId: 'usr_feat_1',
        user: {
          id: 'usr_feat_1',
          username: 'sophia_visuals',
          name: 'Sophia Vance',
          avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
          isVerified: true,
        },
        content: 'The lighting here is breathtaking Alex! That neon violet glow is unreal 💜',
        likesCount: 12,
        createdAt: '2026-03-28T15:10:00.000Z',
      },
    ],
    createdAt: '2026-03-28T14:20:00.000Z',
  },
  {
    id: 'post_02',
    userId: 'usr_feat_1',
    user: {
      id: 'usr_feat_1',
      username: 'sophia_visuals',
      name: 'Sophia Vance',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&h=300&fit=crop&crop=face',
      isVerified: true,
    },
    caption: 'Haute couture editorial series captured during golden hour in Jardin des Tuileries, Paris ✨ Styled with vintage silks and organic textures. #paris #fashion #editorial #portrait',
    location: 'Paris, France',
    visibility: 'public',
    media: [
      {
        id: 'media_02_1',
        userId: 'usr_feat_1',
        postId: 'post_02',
        assetId: 'cld_paris_01',
        publicId: 'beesocial/posts/images/post_02/paris_editorial',
        resourceType: 'image',
        format: 'webp',
        width: 1200,
        height: 1500,
        bytes: 1171745,
        originalUrl: '/pics/pic_11.jpg',
        thumbnailUrl: '/pics/pic_11.jpg',
        optimizedUrl: '/pics/pic_11.jpg',
        folder: 'beesocial/posts/images',
        tags: ['paris', 'fashion', 'editorial', 'portrait'],
        createdAt: '2026-03-29T10:00:00.000Z',
      },
    ],
    likesCount: 1520,
    commentsCount: 42,
    sharesCount: 110,
    isLiked: true,
    isBookmarked: true,
    tags: ['paris', 'fashion', 'editorial', 'portrait'],
    comments: [],
    createdAt: '2026-03-29T10:00:00.000Z',
  },
  {
    id: 'post_03',
    userId: 'usr_feat_3',
    user: {
      id: 'usr_feat_3',
      username: 'elena_captures',
      name: 'Elena Rostova',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop',
      isVerified: true,
    },
    caption: 'Glacier canyon flythrough in Iceland with custom FPV cold tone LUTs 🚁❄️ Pure cinematic isolation. #iceland #drone #glacier #aerial',
    location: 'Vatnajökull, Iceland',
    visibility: 'public',
    media: [
      {
        id: 'media_03_1',
        userId: 'usr_feat_3',
        postId: 'post_03',
        assetId: 'cld_glacier_01',
        publicId: 'beesocial/posts/images/post_03/iceland_glacier',
        resourceType: 'image',
        format: 'webp',
        width: 1200,
        height: 1500,
        bytes: 480100,
        originalUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1600&auto=format&fit=crop',
        thumbnailUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=300&h=300&auto=format&fit=crop',
        optimizedUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1080&auto=format&fit=crop',
        folder: 'beesocial/posts/images',
        tags: ['iceland', 'glacier', 'drone'],
        createdAt: '2026-03-30T06:15:00.000Z',
      },
    ],
    likesCount: 912,
    commentsCount: 31,
    sharesCount: 54,
    isLiked: false,
    isBookmarked: false,
    tags: ['iceland', 'nature', 'aerial'],
    comments: [],
    createdAt: '2026-03-30T06:15:00.000Z',
  },
  {
    id: 'post_04',
    userId: 'usr_feat_2',
    user: {
      id: 'usr_feat_2',
      username: 'marcus_lens',
      name: 'Marcus Chen',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face',
      isVerified: true,
    },
    caption: 'Brutalist concrete vs lush green vertical gardens in Singapore 🌿🏙️ Architecture that breathes with the city. #singapore #architecture #design #minimalism',
    location: 'Marina Bay, Singapore',
    visibility: 'public',
    media: [
      {
        id: 'media_04_1',
        userId: 'usr_feat_2',
        postId: 'post_04',
        assetId: 'cld_singapore_01',
        publicId: 'beesocial/posts/images/post_04/singapore_architecture',
        resourceType: 'image',
        format: 'webp',
        width: 1200,
        height: 1200,
        bytes: 94611,
        originalUrl: '/pics/pic_20.jpeg',
        thumbnailUrl: '/pics/pic_20.jpeg',
        optimizedUrl: '/pics/pic_20.jpeg',
        folder: 'beesocial/posts/images',
        tags: ['singapore', 'architecture', 'design'],
        createdAt: '2026-03-30T16:00:00.000Z',
      },
    ],
    likesCount: 1140,
    commentsCount: 38,
    sharesCount: 72,
    isLiked: true,
    isBookmarked: false,
    tags: ['singapore', 'architecture', 'design'],
    comments: [],
    createdAt: '2026-03-30T16:00:00.000Z',
  },
  {
    id: 'post_05',
    userId: 'usr_feat_4',
    user: {
      id: 'usr_feat_4',
      username: 'kai_cinema',
      name: 'Kai Tanaka',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&h=300&fit=crop&crop=face',
      isVerified: true,
    },
    caption: 'Tokyo midnight neon chase video reel 🌧️ Captured on anamorphic 35mm with high bitrate 4K Cloudinary delivery. Watch in fullscreen with sound on! #tokyo #cinematics #neon',
    location: 'Shinjuku Omoide Yokocho',
    visibility: 'public',
    isReel: true,
    media: [
      {
        id: 'media_05_1',
        userId: 'usr_feat_4',
        postId: 'post_05',
        assetId: 'cld_tokyo_vid_01',
        publicId: 'beesocial/posts/videos/post_05/tokyo_night',
        resourceType: 'video',
        format: 'mp4',
        width: 1080,
        height: 1920,
        duration: 15,
        bytes: 8556210,
        originalUrl: '/videos/reel_01.mp4',
        thumbnailUrl: '/videos/reel_01.mp4#t=0.001',
        optimizedUrl: '/videos/reel_01.mp4',
        folder: 'beesocial/posts/videos',
        tags: ['tokyo', 'neon', 'video', 'cinematics'],
        createdAt: '2026-03-31T20:00:00.000Z',
      },
    ],
    likesCount: 5420,
    commentsCount: 248,
    sharesCount: 510,
    isLiked: false,
    isBookmarked: false,
    tags: ['tokyo', 'cinematics', 'neon'],
    comments: [],
    createdAt: '2026-03-31T20:00:00.000Z',
  },
  {
    id: 'post_06',
    userId: 'usr_feat_6',
    user: {
      id: 'usr_feat_6',
      username: 'chloe_art',
      name: 'Chloe Dupont',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop',
      isVerified: true,
    },
    caption: 'Gold leaf and acrylic honeycomb illustration series 🐝✨ Exploring organic warmth and tactile textures. Exhibition opening this Friday! #art #illustration #botanical',
    location: 'Brooklyn Art District, NY',
    visibility: 'public',
    media: [
      {
        id: 'media_06_1',
        userId: 'usr_feat_6',
        postId: 'post_06',
        assetId: 'cld_art_01',
        publicId: 'beesocial/posts/images/post_06/chloe_honeycomb',
        resourceType: 'image',
        format: 'webp',
        width: 1200,
        height: 1500,
        bytes: 380243,
        originalUrl: '/pics/pic_13.jpg',
        thumbnailUrl: '/pics/pic_13.jpg',
        optimizedUrl: '/pics/pic_13.jpg',
        folder: 'beesocial/posts/images',
        tags: ['art', 'illustration', 'acrylic'],
        createdAt: '2026-04-01T12:00:00.000Z',
      },
    ],
    likesCount: 1890,
    commentsCount: 54,
    sharesCount: 88,
    isLiked: false,
    isBookmarked: false,
    tags: ['art', 'painting', 'botanical'],
    comments: [],
    createdAt: '2026-04-01T12:00:00.000Z',
  },
  {
    id: 'post_07',
    userId: 'usr_feat_12',
    user: {
      id: 'usr_feat_12',
      username: 'noah_wildlife',
      name: 'Noah Sterling',
      avatarUrl: '/pics/pic_09.png',
      isVerified: true,
    },
    caption: 'Majestic bald eagle captured mid-glide over the Chilkat River valley in Alaska 🦅❄️ 600mm f/4 telephoto lens with 1/4000s shutter speed. The detail in every feather is pristine! #wildlife #alaska #nature #birds #conservation',
    location: 'Haines, Alaska',
    visibility: 'public',
    media: [
      {
        id: 'media_07_1',
        userId: 'usr_feat_12',
        postId: 'post_07',
        assetId: 'cld_eagle_01',
        publicId: 'mediagram/posts/images/eagle_alaska',
        resourceType: 'image',
        format: 'jpg',
        width: 1920,
        height: 1280,
        bytes: 6280492,
        originalUrl: '/pics/pic_10.png',
        thumbnailUrl: '/pics/pic_10.png',
        optimizedUrl: '/pics/pic_10.png',
        folder: 'mediagram/posts/images',
        tags: ['wildlife', 'eagle', 'alaska', 'nature'],
        createdAt: '2026-04-02T08:30:00.000Z',
      },
    ],
    likesCount: 4210,
    commentsCount: 189,
    sharesCount: 312,
    isLiked: true,
    isBookmarked: false,
    tags: ['wildlife', 'eagle', 'alaska', 'nature'],
    comments: [],
    createdAt: '2026-04-02T08:30:00.000Z',
  },
  {
    id: 'post_08',
    userId: 'usr_feat_3',
    user: {
      id: 'usr_feat_3',
      username: 'elena_captures',
      name: 'Elena Rostova',
      avatarUrl: '/pics/pic_04.jpg',
      isVerified: true,
    },
    caption: 'Atmospheric monochrome studio portraiture with natural softbox diffusion ✨ 85mm prime lens wide open at f/1.4. Skin tones and shadow roll-off preserved via Cloudinary lossless delivery. #portrait #monochrome #studio #fashion',
    location: 'Milan Fashion District',
    visibility: 'public',
    media: [
      {
        id: 'media_08_1',
        userId: 'usr_feat_3',
        postId: 'post_08',
        assetId: 'cld_portrait_08',
        publicId: 'mediagram/posts/images/elena_studio_portrait',
        resourceType: 'image',
        format: 'jpg',
        width: 1200,
        height: 1600,
        bytes: 631073,
        originalUrl: '/pics/pic_16.jpg',
        thumbnailUrl: '/pics/pic_16.jpg',
        optimizedUrl: '/pics/pic_16.jpg',
        folder: 'mediagram/posts/images',
        tags: ['portrait', 'fashion', 'studio', 'bnw'],
        createdAt: '2026-04-02T11:45:00.000Z',
      },
    ],
    likesCount: 2780,
    commentsCount: 92,
    sharesCount: 145,
    isLiked: false,
    isBookmarked: true,
    tags: ['portrait', 'fashion', 'studio'],
    comments: [],
    createdAt: '2026-04-02T11:45:00.000Z',
  },
  {
    id: 'post_09',
    userId: 'usr_feat_4',
    user: {
      id: 'usr_feat_4',
      username: 'kai_cinema',
      name: 'Kai Tanaka',
      avatarUrl: '/pics/pic_06.png',
      isVerified: true,
    },
    caption: 'Neon alleyways and rainy reflections at 3 AM in Kabukicho 🌧️⚡ Color graded with anamorphic blue flares and deep shadow saturation. Cloudinary dynamic edge sharpening highlights the wet asphalt textures! #cyberpunk #tokyo #cinematics #neon #nightshoot',
    location: 'Kabukicho, Tokyo',
    visibility: 'public',
    media: [
      {
        id: 'media_09_1',
        userId: 'usr_feat_4',
        postId: 'post_09',
        assetId: 'cld_tokyo_neon_09',
        publicId: 'mediagram/posts/images/kai_neon_night',
        resourceType: 'image',
        format: 'jpg',
        width: 1920,
        height: 1080,
        bytes: 1310837,
        originalUrl: '/pics/pic_17.jpg',
        thumbnailUrl: '/pics/pic_17.jpg',
        optimizedUrl: '/pics/pic_17.jpg',
        folder: 'mediagram/posts/images',
        tags: ['tokyo', 'neon', 'cyberpunk', 'cinematics'],
        createdAt: '2026-04-02T15:20:00.000Z',
      },
    ],
    likesCount: 3950,
    commentsCount: 167,
    sharesCount: 280,
    isLiked: false,
    isBookmarked: false,
    tags: ['tokyo', 'neon', 'cyberpunk', 'cinematics'],
    comments: [],
    createdAt: '2026-04-02T15:20:00.000Z',
  },
  {
    id: 'post_10',
    userId: 'usr_feat_7',
    user: {
      id: 'usr_feat_7',
      username: 'maya_studio',
      name: 'Maya Lin',
      avatarUrl: '/pics/pic_08.jpg',
      isVerified: true,
    },
    caption: 'Demon Slayer Nezuko tribute illustration 🌸✨ Custom digital speedpaint using hand-blended gradients and traditional Japanese pattern elements. Process video coming to reels tomorrow! #anime #illustration #demonslayer #nezuko #digitalart',
    location: 'Kyoto Animation Studio',
    visibility: 'public',
    media: [
      {
        id: 'media_10_1',
        userId: 'usr_feat_7',
        postId: 'post_10',
        assetId: 'cld_anime_10',
        publicId: 'mediagram/posts/images/maya_anime_art',
        resourceType: 'image',
        format: 'jpg',
        width: 1920,
        height: 1080,
        bytes: 9318225,
        originalUrl: '/pics/pic_18.jpg',
        thumbnailUrl: '/pics/pic_18.jpg',
        optimizedUrl: '/pics/pic_18.jpg',
        folder: 'mediagram/posts/images',
        tags: ['anime', 'illustration', 'digitalart', 'fanart'],
        createdAt: '2026-04-02T18:10:00.000Z',
      },
    ],
    likesCount: 6890,
    commentsCount: 420,
    sharesCount: 890,
    isLiked: true,
    isBookmarked: true,
    tags: ['anime', 'illustration', 'digitalart', 'fanart'],
    comments: [],
    createdAt: '2026-04-02T18:10:00.000Z',
  },
  {
    id: 'post_11',
    userId: 'usr_feat_1',
    user: {
      id: 'usr_feat_1',
      username: 'sophia_visuals',
      name: 'Sophia Vance',
      avatarUrl: '/pics/pic_01.jpg',
      isVerified: true,
    },
    caption: 'Sunlit rooftop portrait session in Paris ☕🌿 Vintage linen, gentle morning breeze, and unfiltered authentic warmth. #paris #sunlight #lifestyle #portrait #slowliving',
    location: 'Montmartre, Paris',
    visibility: 'public',
    media: [
      {
        id: 'media_11_1',
        userId: 'usr_feat_1',
        postId: 'post_11',
        assetId: 'cld_paris_11',
        publicId: 'mediagram/posts/images/sophia_rooftop',
        resourceType: 'image',
        format: 'jpg',
        width: 1200,
        height: 1600,
        bytes: 2771092,
        originalUrl: '/pics/pic_01.jpg',
        thumbnailUrl: '/pics/pic_01.jpg',
        optimizedUrl: '/pics/pic_01.jpg',
        folder: 'mediagram/posts/images',
        tags: ['paris', 'portrait', 'lifestyle'],
        createdAt: '2026-04-03T09:15:00.000Z',
      },
    ],
    likesCount: 3120,
    commentsCount: 114,
    sharesCount: 180,
    isLiked: false,
    isBookmarked: false,
    tags: ['paris', 'portrait', 'lifestyle'],
    comments: [],
    createdAt: '2026-04-03T09:15:00.000Z',
  },
  {
    id: 'post_12',
    userId: 'usr_feat_2',
    user: {
      id: 'usr_feat_2',
      username: 'marcus_lens',
      name: 'Marcus Chen',
      avatarUrl: '/pics/pic_03.jpg',
      isVerified: true,
    },
    caption: 'Voices of the street — documentary photojournalism series documenting community and city culture 🏙️✊ Shot on Leica M11 with 28mm Summicron lens. #photojournalism #documentary #streetculture #urban',
    location: 'Lower East Side, NY',
    visibility: 'public',
    media: [
      {
        id: 'media_12_1',
        userId: 'usr_feat_2',
        postId: 'post_12',
        assetId: 'cld_street_12',
        publicId: 'mediagram/posts/images/marcus_documentary',
        resourceType: 'image',
        format: 'jpg',
        width: 1400,
        height: 1000,
        bytes: 419501,
        originalUrl: '/pics/pic_03.jpg',
        thumbnailUrl: '/pics/pic_03.jpg',
        optimizedUrl: '/pics/pic_03.jpg',
        folder: 'mediagram/posts/images',
        tags: ['photojournalism', 'documentary', 'streetphotography'],
        createdAt: '2026-04-03T11:00:00.000Z',
      },
    ],
    likesCount: 2450,
    commentsCount: 88,
    sharesCount: 130,
    isLiked: false,
    isBookmarked: false,
    tags: ['photojournalism', 'documentary', 'streetphotography'],
    comments: [],
    createdAt: '2026-04-03T11:00:00.000Z',
  },
  {
    id: 'post_13',
    userId: 'usr_feat_6',
    user: {
      id: 'usr_feat_6',
      username: 'chloe_art',
      name: 'Chloe Dupont',
      avatarUrl: '/pics/pic_02.png',
      isVerified: true,
    },
    caption: 'Fantasy alchemy & mythical enchantress concept painting 🔮✨ Painted using oil-look digital brushes with volumetric fog and rim lighting. What world should she inhabit? #conceptart #fantasy #illustration #digitalpainting',
    location: 'Atelier Chloe, Paris',
    visibility: 'public',
    media: [
      {
        id: 'media_13_1',
        userId: 'usr_feat_6',
        postId: 'post_13',
        assetId: 'cld_witch_13',
        publicId: 'mediagram/posts/images/chloe_enchantress',
        resourceType: 'image',
        format: 'jpg',
        width: 1920,
        height: 1080,
        bytes: 380243,
        originalUrl: '/pics/pic_13.jpg',
        thumbnailUrl: '/pics/pic_13.jpg',
        optimizedUrl: '/pics/pic_13.jpg',
        folder: 'mediagram/posts/images',
        tags: ['conceptart', 'fantasy', 'illustration'],
        createdAt: '2026-04-03T13:30:00.000Z',
      },
    ],
    likesCount: 3670,
    commentsCount: 204,
    sharesCount: 220,
    isLiked: true,
    isBookmarked: false,
    tags: ['conceptart', 'fantasy', 'illustration'],
    comments: [],
    createdAt: '2026-04-03T13:30:00.000Z',
  },
  {
    id: 'post_14',
    userId: 'usr_feat_9',
    user: {
      id: 'usr_feat_9',
      username: 'leo_craft',
      name: 'Leo Thorne',
      avatarUrl: '/pics/pic_07.jpg',
      isVerified: true,
    },
    caption: 'Macro botanical study and leaf textures under morning dew 🌿💧 Captured with Sony 90mm Macro G Master lens. Micro-contrast optimized for ultra-crisp mobile display! #macro #nature #texture #botanical #photography',
    location: 'Pacific Northwest Rainforest',
    visibility: 'public',
    media: [
      {
        id: 'media_14_1',
        userId: 'usr_feat_9',
        postId: 'post_14',
        assetId: 'cld_macro_14',
        publicId: 'mediagram/posts/images/leo_macro_nature',
        resourceType: 'image',
        format: 'png',
        width: 1920,
        height: 1080,
        bytes: 767494,
        originalUrl: '/pics/pic_12.jpg',
        thumbnailUrl: '/pics/pic_12.jpg',
        optimizedUrl: '/pics/pic_12.jpg',
        folder: 'mediagram/posts/images',
        tags: ['macro', 'nature', 'botanical'],
        createdAt: '2026-04-03T14:45:00.000Z',
      },
    ],
    likesCount: 1980,
    commentsCount: 65,
    sharesCount: 78,
    isLiked: false,
    isBookmarked: true,
    tags: ['macro', 'nature', 'botanical'],
    comments: [],
    createdAt: '2026-04-03T14:45:00.000Z',
  },
];

// Map all 33 creator video reels as posts so creators own both their individual posts and reels
const REEL_POSTS: Post[] = SEED_REELS.map((reel) => ({
  id: reel.postId,
  userId: reel.userId,
  user: reel.user,
  caption: reel.caption,
  location: 'Studio / Location Reel',
  visibility: 'public',
  isReel: true,
  media: [
    {
      id: `media_${reel.id}`,
      userId: reel.userId,
      postId: reel.postId,
      assetId: `cld_${reel.id}`,
      publicId: `beesocial/reels/${reel.id}`,
      resourceType: 'video' as const,
      format: 'mp4',
      width: 1080,
      height: 1920,
      duration: reel.duration,
      bytes: 8500000,
      originalUrl: reel.videoUrl,
      thumbnailUrl: reel.posterUrl,
      optimizedUrl: reel.videoUrl,
      folder: 'beesocial/reels',
      tags: ['reel', 'video', 'creator'],
      createdAt: reel.createdAt,
    },
  ],
  likesCount: reel.likesCount,
  commentsCount: reel.commentsCount,
  sharesCount: reel.sharesCount,
  isLiked: reel.isLiked,
  isBookmarked: reel.isBookmarked,
  tags: ['reel', 'video', 'creator'],
  comments: [],
  createdAt: reel.createdAt,
}));

export const SEED_POSTS: Post[] = [...INITIAL_PHOTO_POSTS, ...REEL_POSTS];
