export interface PresetVideoClip {
  id: string;
  filename: string;
  videoUrl: string;
  title: string;
  caption: string;
  tags: string[];
  suggestedLocation: string;
  audioTrackTitle: string;
  creatorUsername: string;
  likesCount: number;
  commentsCount: number;
  viewsCount: number;
  duration: number;
}

export const PRESET_VIDEO_CLIPS: PresetVideoClip[] = [
  {
    id: 'vid_01',
    filename: 'reel_01.mp4',
    videoUrl: '/videos/reel_01.mp4',
    title: 'Midnight Tokyo Hyperlapse Chase',
    caption: 'Tokyo rain hyperlapse through Shibuya & Shinjuku at 2 AM 🌧️ Speed, reflections, and cyberpunk atmosphere. Shot on 35mm anamorphic.',
    tags: ['tokyo', 'cyberpunk', 'hyperlapse', 'cinematics', 'nightlife'],
    suggestedLocation: 'Shibuya Crossing, Tokyo',
    audioTrackTitle: 'Kai Tanaka · Tokyo Midnight Synthwave Remix',
    creatorUsername: 'kai_cinema',
    likesCount: 5420,
    commentsCount: 248,
    viewsCount: 48900,
    duration: 15,
  },
  {
    id: 'vid_02',
    filename: 'reel_02.mp4',
    videoUrl: '/videos/reel_02.mp4',
    title: 'Bumblebee Botanical Illustration',
    caption: 'Macro bumblebee and honeycomb painting process 🐝🌼 Bringing warmth and tactile texture with gold leaf details.',
    tags: ['art', 'bumblebee', 'illustration', 'painting', 'botanical'],
    suggestedLocation: 'Brooklyn Art District, NY',
    audioTrackTitle: 'Chloe Dupont · Acoustic Honeycomb Groove',
    creatorUsername: 'chloe_art',
    likesCount: 3890,
    commentsCount: 164,
    viewsCount: 34200,
    duration: 14,
  },
  {
    id: 'vid_03',
    filename: 'reel_03.mp4',
    videoUrl: '/videos/reel_03.mp4',
    title: 'Coconut Tropical Summer Mood',
    caption: 'Sunny island breeze with fresh coconuts 🥥🌴 Sometimes you just need tropical sunshine and gentle waves.',
    tags: ['coconut', 'summer', 'tropical', 'beach', 'vacation'],
    suggestedLocation: 'Maui, Hawaii',
    audioTrackTitle: 'Island Drift · Coconut Wave Acoustic',
    creatorUsername: 'customer',
    likesCount: 4120,
    commentsCount: 182,
    viewsCount: 41000,
    duration: 12,
  },
  {
    id: 'vid_04',
    filename: 'reel_04.mp4',
    videoUrl: '/videos/reel_04.mp4',
    title: 'Dancing Parrots Rhythm Session',
    caption: 'When the beat drops and the whole flock can’t resist dancing! 🦜✨ Synchronized feather groove.',
    tags: ['dance', 'birds', 'parrots', 'cute', 'viral'],
    suggestedLocation: 'Botanical Sanctuary, Costa Rica',
    audioTrackTitle: 'Samba Feathers · Tropical Rhythm Mix',
    creatorUsername: 'elena_captures',
    likesCount: 6890,
    commentsCount: 312,
    viewsCount: 62400,
    duration: 13,
  },
  {
    id: 'vid_05',
    filename: 'reel_05.mp4',
    videoUrl: '/videos/reel_05.mp4',
    title: 'Honey Bunny Playful Bounce',
    caption: 'Pure weekend joy! Jumping around and spreading fluffy smiles 🐰🤪 Sound up for happy vibes!',
    tags: ['bunny', 'cute', 'fluffy', 'funny', 'pets'],
    suggestedLocation: 'Cotswolds, UK',
    audioTrackTitle: 'Sugar Pop · Happy Bounce Anthem',
    creatorUsername: 'maya_style',
    likesCount: 7120,
    commentsCount: 420,
    viewsCount: 78500,
    duration: 11,
  },
  {
    id: 'vid_06',
    filename: 'reel_06.mp4',
    videoUrl: '/videos/reel_06.mp4',
    title: 'Ivy Dancing For You',
    caption: 'Ivy taking the stage with her special choreo! 🐰♥️ The cutest routine to brighten your feed today.',
    tags: ['danceai', 'bunnylove', 'cuteanimals', 'animation', 'choreography'],
    suggestedLocation: 'Dream Studios, LA',
    audioTrackTitle: 'Ivy Choreo · Sweet Electro Swing',
    creatorUsername: 'sophia_visuals',
    likesCount: 8940,
    commentsCount: 512,
    viewsCount: 96000,
    duration: 16,
  },
  {
    id: 'vid_07',
    filename: 'reel_07.mp4',
    videoUrl: '/videos/reel_07.mp4',
    title: 'Jaane Meriye Anime Illustration',
    caption: 'Soft golden hour 2D anime illustration process 🌸🤌 Digital line work and dreamy pastel blending.',
    tags: ['digitalart', 'anime', 'illustration', 'aesthetic', 'procreate'],
    suggestedLocation: 'Kyoto Creative Hub, Japan',
    audioTrackTitle: 'Lo-Fi Chill · Jaane Meriye Melody',
    creatorUsername: 'marcus_lens',
    likesCount: 4720,
    commentsCount: 204,
    viewsCount: 43000,
    duration: 12,
  },
  {
    id: 'vid_08',
    filename: 'reel_08.mp4',
    videoUrl: '/videos/reel_08.mp4',
    title: 'Kittens Dance Show Premiere',
    caption: 'The tiny paws performance everyone has been waiting for! 🐱💃 Who taught them these moves?!',
    tags: ['cat', 'kitten', 'catsofinstagram', 'dance', 'wholesome'],
    suggestedLocation: 'Cat Cafe, Seoul',
    audioTrackTitle: 'Purr Rhythm · Kitten Disco Groove',
    creatorUsername: 'zara_sound',
    likesCount: 9540,
    commentsCount: 680,
    viewsCount: 112000,
    duration: 14,
  },
  {
    id: 'vid_09',
    filename: 'reel_09.mp4',
    videoUrl: '/videos/reel_09.mp4',
    title: 'Kittens Dance Encore',
    caption: 'Back with the full choreography! Synchronized purrs and tiny head bobs 🐾🎵',
    tags: ['cats', 'kittens', 'funnycats', 'pets', 'dance'],
    suggestedLocation: 'Meow Manor, Paris',
    audioTrackTitle: 'Tiny Paws Big Beat · Funky Kittens',
    creatorUsername: 'liam_wander',
    likesCount: 8430,
    commentsCount: 520,
    viewsCount: 89000,
    duration: 15,
  },
  {
    id: 'vid_10',
    filename: 'reel_10.mp4',
    videoUrl: '/videos/reel_10.mp4',
    title: 'Funny Kittens Dance Takeover',
    caption: 'When mom leaves the room and the kittens turn into party legends 🐱🕺',
    tags: ['catlover', 'kitty', 'funny', 'reels', 'pets'],
    suggestedLocation: 'Tokyo Cat Island',
    audioTrackTitle: 'Meow Funk · Party Kittens Remix',
    creatorUsername: 'noah_frames',
    likesCount: 7890,
    commentsCount: 390,
    viewsCount: 84000,
    duration: 13,
  },
  {
    id: 'vid_11',
    filename: 'reel_11.mp4',
    videoUrl: '/videos/reel_11.mp4',
    title: 'Lonely Tere Bin Sketch Journal',
    caption: 'Late night sketching emotions with loose ink and watercolor washes ✍️🎨 Drawing what cannot be said.',
    tags: ['doodle', 'sketch', 'drawing', 'artist', 'memes'],
    suggestedLocation: 'Berlin Studio',
    audioTrackTitle: 'Acoustic Rain · Melodic Doodles',
    creatorUsername: 'sophia_visuals',
    likesCount: 5120,
    commentsCount: 278,
    viewsCount: 53000,
    duration: 12,
  },
  {
    id: 'vid_12',
    filename: 'reel_12.mp4',
    videoUrl: '/videos/reel_12.mp4',
    title: 'Love Me Not Typography Motion',
    caption: 'Wiggly paint digital brush lettering 🚫 Dynamic typography animated frame by frame in 4K.',
    tags: ['typography', 'digitalart', 'lettering', 'animation', 'design'],
    suggestedLocation: 'London Design Week',
    audioTrackTitle: 'Glitch Pop · Dynamic Lettering Beats',
    creatorUsername: 'chloe_art',
    likesCount: 4210,
    commentsCount: 195,
    viewsCount: 39500,
    duration: 10,
  },
  {
    id: 'vid_13',
    filename: 'reel_13.mp4',
    videoUrl: '/videos/reel_13.mp4',
    title: 'Sachme Ek Bhi Nahi Comic',
    caption: 'That ultra relatable moment when expectations meet brutal hilarious reality 😂 Tag that one friend!',
    tags: ['funny', 'relatable', 'comedy', 'humor', 'memes'],
    suggestedLocation: 'Mumbai, India',
    audioTrackTitle: 'Comedy Punch · Sitcom Groove',
    creatorUsername: 'customer',
    likesCount: 6340,
    commentsCount: 340,
    viewsCount: 71000,
    duration: 9,
  },
  {
    id: 'vid_14',
    filename: 'reel_14.mp4',
    videoUrl: '/videos/reel_14.mp4',
    title: 'Spontaneous Coffee Doodles',
    caption: 'Drawing cute encounters in crowded cafes ☕💭 Secret sketches that capture warm human connection.',
    tags: ['doodlesofinstagram', 'doodle', 'coffee', 'art', 'cafe'],
    suggestedLocation: 'SoHo, Manhattan',
    audioTrackTitle: 'Morning Espresso · Chill Lofi Keys',
    creatorUsername: 'maya_style',
    likesCount: 5820,
    commentsCount: 260,
    viewsCount: 59000,
    duration: 10,
  },
  {
    id: 'vid_15',
    filename: 'reel_15.mp4',
    videoUrl: '/videos/reel_15.mp4',
    title: 'Family Humor & Relatable Drama',
    caption: 'Comedic timing at family gatherings that hits way too close to home 🙏🏻😂 Send this to your family group!',
    tags: ['instagramreels', 'instadaily', 'funny', 'reels', 'humor'],
    suggestedLocation: 'New Delhi, India',
    audioTrackTitle: 'Laugh Track · Indian Comedy Mashup',
    creatorUsername: 'marcus_lens',
    likesCount: 6920,
    commentsCount: 380,
    viewsCount: 76000,
    duration: 12,
  },
  {
    id: 'vid_16',
    filename: 'reel_16.mp4',
    videoUrl: '/videos/reel_16.mp4',
    title: 'Kitten Crew Backup Dancers',
    caption: 'The squad has fully assembled! Backing up the main star with serious rhythm 🐾✨',
    tags: ['cats', 'funnycats', 'dance', 'cats_of_instagram', 'viral'],
    suggestedLocation: 'Amsterdam, Netherlands',
    audioTrackTitle: 'Feline Funk · Cat Troupe Choreography',
    creatorUsername: 'elena_captures',
    likesCount: 8740,
    commentsCount: 460,
    viewsCount: 92000,
    duration: 14,
  },
  {
    id: 'vid_17',
    filename: 'reel_17.mp4',
    videoUrl: '/videos/reel_17.mp4',
    title: 'Kittens Group Formation',
    caption: 'Practice makes purrfect! Watch the center kitten nail the spin at second 0:08 🐱💃',
    tags: ['kitten', 'dance', 'catsofinstagram', 'cute', 'pets'],
    suggestedLocation: 'Osaka, Japan',
    audioTrackTitle: 'Purr Beats · Synchronized Paws',
    creatorUsername: 'kai_cinema',
    likesCount: 7620,
    commentsCount: 390,
    viewsCount: 81000,
    duration: 13,
  },
  {
    id: 'vid_18',
    filename: 'reel_18.mp4',
    videoUrl: '/videos/reel_18.mp4',
    title: 'Pug Puppies Wedding Walk Date',
    caption: 'These pug puppies just had the sweetest little wedding walk! Tiny bowties and happy tail wiggles 🐶💍',
    tags: ['doglover', 'pugs', 'dogs', 'trending', 'cute'],
    suggestedLocation: 'Central Park, NYC',
    audioTrackTitle: 'Wedding Bells For Pugs · Sweet Ukulele',
    creatorUsername: 'customer',
    likesCount: 11200,
    commentsCount: 780,
    viewsCount: 134000,
    duration: 13,
  },
  {
    id: 'vid_19',
    filename: 'reel_19.mp4',
    videoUrl: '/videos/reel_19.mp4',
    title: 'Tum Ha Tum Doggy Mischief',
    caption: 'That face your pup makes right after stealing your favorite sock from the laundry pile 🫵🏻🐶',
    tags: ['dogs', 'puppy', 'dogsofinstagram', 'funny', 'cute'],
    suggestedLocation: 'Vancouver, Canada',
    audioTrackTitle: 'Guilty Paws · Playful Dog Whistle',
    creatorUsername: 'liam_wander',
    likesCount: 6840,
    commentsCount: 310,
    viewsCount: 72000,
    duration: 10,
  },
  {
    id: 'vid_20',
    filename: 'reel_20.mp4',
    videoUrl: '/videos/reel_20.mp4',
    title: 'Playful Pup Loyalty',
    caption: 'The definition of unconditional love: always waiting by the door with a wagging tail 🐾♥️',
    tags: ['dog', 'bestfriend', 'pets', 'wholesome', 'puppies'],
    suggestedLocation: 'Sydney, Australia',
    audioTrackTitle: 'Warm Sunshine · Acoustic Dog Days',
    creatorUsername: 'noah_frames',
    likesCount: 6410,
    commentsCount: 290,
    viewsCount: 67000,
    duration: 10,
  },
  {
    id: 'vid_21',
    filename: 'reel_21.mp4',
    videoUrl: '/videos/reel_21.mp4',
    title: 'Slow Motion Golden Hour Capture',
    caption: 'Cinematic sunlight cascading through glass and dust motes. High bitrate 60fps slow motion test 🌅📹',
    tags: ['cinematography', 'goldenhour', 'filmmaking', 'lensflare', '4k'],
    suggestedLocation: 'Joshua Tree, California',
    audioTrackTitle: 'Sunset Drift · Ambient Atmospheric Score',
    creatorUsername: 'marcus_lens',
    likesCount: 7340,
    commentsCount: 310,
    viewsCount: 78000,
    duration: 15,
  },
  {
    id: 'vid_22',
    filename: 'reel_22.mp4',
    videoUrl: '/videos/reel_22.mp4',
    title: 'Kittens Alone in the Room',
    caption: 'Camera footage revealed the secret nightlife of kittens when humans fall asleep! 🐱👀 Total energetic zoomies.',
    tags: ['kittens', 'cats', 'secretlife', 'funny', 'pets'],
    suggestedLocation: 'Stockholm, Sweden',
    audioTrackTitle: 'Midnight Zoomies · Electro Cat Pop',
    creatorUsername: 'zara_sound',
    likesCount: 8910,
    commentsCount: 450,
    viewsCount: 94000,
    duration: 14,
  },
  {
    id: 'vid_23',
    filename: 'reel_23.mp4',
    videoUrl: '/videos/reel_23.mp4',
    title: 'Certified Foodie Dilemma',
    caption: 'When your heart says diet but your soul says pastry and gourmet pasta 🥐🍝 Every bite is pure happiness!',
    tags: ['foodie', 'delicious', 'foodstagram', 'comedy', 'yum'],
    suggestedLocation: 'Rome, Italy',
    audioTrackTitle: 'Buon Appetito · Italian Accordion Swing',
    creatorUsername: 'sophia_visuals',
    likesCount: 5490,
    commentsCount: 280,
    viewsCount: 61000,
    duration: 10,
  },
  {
    id: 'vid_24',
    filename: 'reel_24.mp4',
    videoUrl: '/videos/reel_24.mp4',
    title: 'Holding In The Name Gossip',
    caption: 'Trying so hard not to spill the tea when someone asks about your weekend plans 👀😂 Peak drama expression.',
    tags: ['funnyreels', 'relatable', 'comedy', 'friends', 'viral'],
    suggestedLocation: 'Austin, Texas',
    audioTrackTitle: 'Spill The Tea · Dramatic Bass Drop',
    creatorUsername: 'customer',
    likesCount: 6820,
    commentsCount: 370,
    viewsCount: 73000,
    duration: 11,
  },
  {
    id: 'vid_25',
    filename: 'reel_25.mp4',
    videoUrl: '/videos/reel_25.mp4',
    title: 'Darling Angel Baby Aesthetic',
    caption: 'Soft aesthetic memories captured on retro 16mm grain 😘 Warm sunlight, sweet melodies, and peaceful thoughts.',
    tags: ['aesthetic', 'reelsfeelit', 'vintage', 'love', 'mood'],
    suggestedLocation: 'Santorini, Greece',
    audioTrackTitle: 'Darling Angel · Acoustic Guitar Reverie',
    creatorUsername: 'maya_style',
    likesCount: 6120,
    commentsCount: 290,
    viewsCount: 66000,
    duration: 11,
  },
  {
    id: 'vid_26',
    filename: 'reel_26.mp4',
    videoUrl: '/videos/reel_26.mp4',
    title: 'Morning Coffee Cartoon Routine',
    caption: 'The old coffee mug broke so the new warrior stepped up! 😂☕🍪 Relatable morning struggles animated.',
    tags: ['coffee', 'aicartoon', 'funny', 'morningroutine', 'animation'],
    suggestedLocation: 'Seattle, WA',
    audioTrackTitle: 'Caffeine Rush · Cartoon Morning Whistle',
    creatorUsername: 'elena_captures',
    likesCount: 5340,
    commentsCount: 240,
    viewsCount: 58000,
    duration: 11,
  },
  {
    id: 'vid_27',
    filename: 'reel_27.mp4',
    videoUrl: '/videos/reel_27.mp4',
    title: 'Pooh and Gini Puppy Drama',
    caption: 'He thought he was the neighborhood hero until the little dog taught him a lesson! 😂🐶 Pooh & Gini comedy.',
    tags: ['dogs', 'dogsofinstagram', 'funnyanimals', 'pets', 'comedy'],
    suggestedLocation: 'Miami, Florida',
    audioTrackTitle: 'Heroic Fumble · Cartoon Trombone',
    creatorUsername: 'liam_wander',
    likesCount: 7420,
    commentsCount: 390,
    viewsCount: 82000,
    duration: 13,
  },
  {
    id: 'vid_28',
    filename: 'reel_28.mp4',
    videoUrl: '/videos/reel_28.mp4',
    title: 'Himouto Umaru-Chan Anime Vibe',
    caption: 'Cozy weekend mode activated: hoodie on, cola in hand, snacks ready 🍿🎮 Ultimate slice-of-life relaxation.',
    tags: ['anime', 'sliceoflife', 'cozy', 'otaku', 'weekend'],
    suggestedLocation: 'Akihabara, Tokyo',
    audioTrackTitle: 'Cola & Crisps · Chibi Anime Jam',
    creatorUsername: 'kai_cinema',
    likesCount: 6890,
    commentsCount: 420,
    viewsCount: 75000,
    duration: 12,
  },
  {
    id: 'vid_29',
    filename: 'reel_29.mp4',
    videoUrl: '/videos/reel_29.mp4',
    title: 'Ghilli High-Energy Stadium Action',
    caption: 'Adrenaline pumping through the stadium! Unstoppable velocity and cinematic sports intensity 🎬🏟️',
    tags: ['sports', 'action', 'cinema', 'energy', 'hype'],
    suggestedLocation: 'Chennai Stadium, India',
    audioTrackTitle: 'Adrenaline Surge · Stadium Anthem',
    creatorUsername: 'marcus_lens',
    likesCount: 8490,
    commentsCount: 510,
    viewsCount: 97000,
    duration: 16,
  },
  {
    id: 'vid_30',
    filename: 'reel_30.mp4',
    videoUrl: '/videos/reel_30.mp4',
    title: 'Rickshawala Street Dance Beat',
    caption: 'Vibrant local street rhythm with infectious foot-tapping beats! 🎵🛺 Celebrating festive joy and culture.',
    tags: ['dance', 'music', 'streetbeats', 'joy', 'celebration'],
    suggestedLocation: 'Pune, Maharashtra',
    audioTrackTitle: 'Vaat Majhi Baghtoy · Folk Rhythm Remix',
    creatorUsername: 'chloe_art',
    likesCount: 7120,
    commentsCount: 360,
    viewsCount: 78000,
    duration: 11,
  },
  {
    id: 'vid_31',
    filename: 'reel_31.mp4',
    videoUrl: '/videos/reel_31.mp4',
    title: 'Wild Outdoors Comic Encounter',
    caption: 'Nature is beautiful but sometimes it has the most comedic jump scares! 🐍😂😂 Sound reaction is legendary.',
    tags: ['outdoors', 'nature', 'funny', 'wildlife', 'reaction'],
    suggestedLocation: 'Everglades, Florida',
    audioTrackTitle: 'Sudden Jolt · Comic Suspense Track',
    creatorUsername: 'customer',
    likesCount: 8940,
    commentsCount: 610,
    viewsCount: 104000,
    duration: 12,
  },
  {
    id: 'vid_32',
    filename: 'reel_32.mp4',
    videoUrl: '/videos/reel_32.mp4',
    title: 'Retro Synthwave Cat Dance',
    caption: 'Taking it back to 2020 with neon cyber cat choreo 🐱🕺 Synthwave grids, chrome gradients, and retro nostalgia.',
    tags: ['ai', 'cat', 'dance', 'synthwave', 'cyberpunk'],
    suggestedLocation: 'Neo Tokyo Virtual Stage',
    audioTrackTitle: 'Synth Meow 2020 · Retrowave Dance',
    creatorUsername: 'zara_sound',
    likesCount: 9240,
    commentsCount: 530,
    viewsCount: 108000,
    duration: 13,
  },
  {
    id: 'vid_33',
    filename: 'reel_33.mp4',
    videoUrl: '/videos/reel_33.mp4',
    title: 'POV: You Cannot Stop Dancing',
    caption: 'POV: That beat is just way too infectious and your feet move on their own! 🐰💃 Unstoppable bounce!',
    tags: ['dance', 'funny', 'bunnylife', 'viral', 'mood'],
    suggestedLocation: 'Seoul Dance District',
    audioTrackTitle: 'Left Right Dance · Viral Electro Bounce',
    creatorUsername: 'noah_frames',
    likesCount: 10450,
    commentsCount: 720,
    viewsCount: 128000,
    duration: 14,
  },
];
